# Build stage
FROM maven:3.6.1-jdk-8-alpine as build
ARG CATALOG_PATH
WORKDIR /app

# Copy parent files
COPY pom.xml .
COPY .env .env

# Copy child modules needed
COPY seisan-quakeml-commons-jpa ./seisan-quakeml-commons-jpa
COPY converter-core ./converter-core
COPY seisan-quakeml-commons-file ./seisan-quakeml-commons-file
COPY quakeml-web-service-ingestor-executable ./quakeml-web-service-ingestor-executable

# Build the application with maven
RUN mvn clean install -P ing-container -Dspring.profiles.active=container


# Deployment stage
FROM anapsix/alpine-java as production
ARG CATALOG_PATH
WORKDIR /app
COPY --from=build /app/quakeml-web-service-ingestor-executable/target/quakeml-web-service-ingestor-executable-1.0.0-SNAPSHOT.jar /app/ingestor.jar