spring:jpa.open-in-view: false
server.error.whitelabel.enabled: false
page.profile: ${profile:nnsn}

spring:
  profiles:
    active: '@spring.profiles.active@'
---
spring.config.activate.on-profile: prod
database:
  address: localhost
  port: 3306
  name: ${env.DB_NAME}
  username: ${env.DB_USER}
  password: ${env.DB_PW}
---
spring.config.activate.on-profile: container
database:
  address: mysql-db
  port: 3306
  name: ${env.DB_NAME}
  username: ${env.DB_USER}
  password: ${env.DB_PW}



