spring:
  profiles:
    active: '@active.profile@'
---
spring:
  profiles: prod
database:
  address: localhost
  port: 3306
  name: intaros
  username: epos
  password: epos
---
spring:
  profiles: container
database:
  address: mysql-db
  port: 3306
  name: intaros
  username: epos
  password: epos
