global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'nor2qml-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
        labels:
          alias: 'prometheus'

  - job_name: 'spring-boot-app'
    metrics_path: '/eqcat/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['spring-boot-app:8090']
        labels:
          alias: 'spring-boot-app'