global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'nor2qml-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot'
    metrics_path: '/eqcat/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.112.3:8090']